CREATE TABLE Team_Lab1
(
	tID INT AUTO_INCREMENT,
	tName VARCHAR(50) NOT NULL,
	CONSTRAINT ID
		PRIMARY KEY (tID)
) ENGINE=InnoDB;

CREATE TABLE Course_Lab1
(
	cID INT AUTO_INCREMENT,
	cName VARCHAR(50) NOT NULL,
	tID INT,
	CONSTRAINT ID
		PRIMARY KEY (cID),
	CONSTRAINT REF_Team
		FOREIGN KEY (tID)
		REFERENCES Team_Lab1 (tID)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE Trainee_Lab1
(
	sID INT AUTO_INCREMENT,
	sName VARCHAR(50) NOT NULL,
	sTel VARCHAR(20),
	sAddress VARCHAR(255),
	cID INT,
	CONSTRAINT IDs
		PRIMARY KEY (sID),
	CONSTRAINT REF_Course
		FOREIGN KEY (cID)
		REFERENCES Course_Lab1 (cID)
		ON UPDATE CASCADE
		ON DELETE SET NULL
) ENGINE = InnoDB;

CREATE TABLE Assignment_Lab1
(
	tID INT NOT NULL,
	iID INT NOT NULL,
	CONSTRAINT REF_Team
		FOREIGN KEY (tID)
		REFERENCES Team_Lab1 (tID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT REF_Instructor
		FOREIGN KEY (iID)
		REFERENCES Ins_Lab1 (iID)
		ON UPDATE CASCADE
		ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Ins_Lab1
(
	iID INT AUTO_INCREMENT,
	iName VARCHAR(50) NOT NULL,
	iAddress VARCHAR(255),
	iTel VARCHAR (20),
	CONSTRAINT ID
		PRIMARY KEY (iID)
) ENGINE=InnoDB;
